### ISSUE TITLE
Design and implement front end badge templates

### ISSUE THREAD

**Issue by Corbzilla** [Prodigious-Aim-Solutions/inroad#2]
Partially designed, not implemented, need some templates for displaying badges earned

**Comment by Corbzilla** [comment]
basic implementation is complete, need design for generic badge template

@AshleyCB @kiefer999 interested?

Should design be a separate issue?

**Comment by Corbzilla** [comment]
Initial implementation is complete, still need proper design for badges, kicking design to v 0.2.0

**Comment by Corbzilla** [comment]
Kicked this to v 0.3.0, also need a view for displaying the current users earned badges and checkins

**Comment by Corbzilla** [comment]
http://webdesignledger.com/freebies/10-free-vintage-retro-badges

Here are the PSDs for the badges, just need to remove the text, we will add it programatically and cut the badges out for use in the app.

**Comment by kiefer999** [comment]
I cut out the badges and removed the text. I also made two versions of each
badge; with and without the crinkled grunge effect. Where is the best place
to upload them?

**Comment by Corbzilla** [comment]
Just email them to me is probably easiest prodigious.aim@gmail.com, I'll add them in.

**Comment by Corbzilla** [comment]
cutout badges look pretty awesome @kiefer999.
need maybe a little writeup for the various types and levels of badges, @AshleyCB you want to do a couple?

ie Historic Level 1 - Wow you really like history don't you. You've been to X amount of historic sites and we're celebrating that with you.

Need Historic 1, 2,3 and Parks 1,2,3

**Comment by Corbzilla** [comment]
I'm working on this now and including a basic user profile to the app.
