### ISSUE TITLE
Live Site - Login not working

### ISSUE THREAD

**Issue by Corbzilla** [Prodigious-Aim-Solutions/inroad#35]
The login is not working on the live site. An initial investigation of this issue determined that the problem lies with the version of PyJWT that is currently used on OpenShift, this version doesn't seem to have a properly functioning encode function which causes an error. Resolution will be either to roll back the development version to the openshift verion 0.4.1ish and modify encode to fit or work to manually install the > 1.0.0 version on openshift

**Comment by AshleyCB** [comment]
which one is this?  ns adventures?

**Comment by Corbzilla** [comment]
Yup, unfortunately its the current live site novascotiaadventures-annotator.rhcloud.com. After trying a few things we this, it appears to be an issue with the openshift platform itself. May have to move the livesite to AWS or some other platform we have more control over.
